### PR TITLE
THRIFT-3535 library_prefix generator argument

### PR DESCRIPTION
**Pull request by markerickson-wf**
CODE REVIEW

Add an argument `library_prefix` to generate files and imports that are usable in an existing Dart library.

This produces a file structure like:

```
gen-dart/
    tutorial.dart
    tutorial/
        calculator.dart
        invalid_operation.dart  
        operation.dart
        tutorial_constants.dart
        work.dart
```

https://issues.apache.org/jira/browse/THRIFT-3535

@ericklaus-wf
@travissanderson-wf

@evanweible-wf
@stevenosborne-wf
@tylertreat-wf

### CODE REVIEW

**Comment by ericklaus-wf** [comment]
+1 Thanks, this will definitely be helpful!

**Comment by travissanderson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by markerickson-wf** [comment]
Thanks, code review complete, I'll PR to Apache.

**Pull request closed without merging**
