### PR TITLE
Build files, Integration test, and Bugfixes

### PR DESCRIPTION
**Pull request by markerickson-wf**
- Added Dart support in build files.  
- Integration tests working with Python Server on buffered transport.  
- Fixed bug in generator with iterating over maps.  
- Fixed typo in Python test server.  
- Discovered bug in FramedTransport, and fixed it. 
- Make TClientSocketTransport simple and add TAsyncClientSocketTransport. 

@evanweible-wf
@tylertreat-wf
@stevenosborne-wf

### CODE REVIEW

**Comment by markerickson-wf** [comment]
Ran the integration test and found another issue after merging in master, investigating...
Confirmed that this test failure only happens after the commit where I merged in master.

**Comment by markerickson-wf** [comment]
It was my problem with the context stack in the JSON protocol, and fixed in https://github.com/markerickson-wf/thrift/commit/c89d1d1fbbbe6747285ef22e7b0faf6623c74d1c .  This is ready for review now.

@evanweible-wf
@tylertreat-wf
@stevenosborne-wf

**Comment by stevenosborne-wf** [comment]
+1

**Comment by stevenosborne-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Pull request merged**
