### PR TITLE
Cleanup TSocketTransport and related code

### PR DESCRIPTION
**Pull request by markerickson-wf**
https://issues.apache.org/jira/browse/THRIFT-3299
- Moved completer logic from WebSocket implementations to transport.  
- Split TSocketTransport into TClientSocketTransport and TServerSocketTransport to cleanup some conditional logic.
- Added a TODO to call out the need to correlate socket requests + responses

@tylertreat-wf
@evanweible-wf
@stevenosborne-wf

### CODE REVIEW

**Comment by markerickson-wf** [comment]
I'm considering moving just the Base64 encoding back into the TWebSocket implementations, since that is specific to that type of socket, and probably shouldn't be generalized in TSocketTransport.

**Comment by markerickson-wf** [comment]
I moved the Base 64 encoding back in https://github.com/markerickson-wf/thrift/commit/4a5197e97fa504e33c2e020a1be5c8f10e8318ca .  This is ready for review now.

**Comment by evanweible-wf** [comment]
+1

**Comment by stevenosborne-wf** [comment]
+1

**Pull request merged**
