### PR TITLE
THRIFT-3697 Name imports from dependencies to avoid naming collisions

### PR DESCRIPTION
**Pull request by markerickson-wf**
Name Dart imports to avoid name collisions.

https://issues.apache.org/jira/browse/THRIFT-3697

@ericklaus-wf
@evanweible-wf
@stevenosborne-wf
@tylertreat-wf

### CODE REVIEW

**Comment by tylertreat-wf** [comment]
+1

**Comment by ericklaus-wf** [comment]
+1

**Comment by stevenosborne-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by markerickson-wf** [comment]
Committed to Apache https://github.com/apache/thrift/commit/b52d03d7a0c1ff2c1fe31c3999127d2daf98bc93

**Pull request closed without merging**
